---
Name: templatetagsconfig
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\View\SSTemplateParser:
    properties:
      closedBlocks:
        template: ['\Moo\Template\Parser\TemplateBlock', 'template']
        set: ['\Moo\Template\Parser\TemplateBlock', 'set']
        spaceless: ['\Moo\Template\Parser\Spaceless', 'spaceless']
      openBlocks:
        content: ['\Moo\Template\Parser\TemplateBlock', 'content']

SilverStripe\ORM\FieldType\DBString:
  extensions:
    - Moo\Template\Extension\SpacelessCast
